### ISSUE TITLE
Incompability vid stomp.py 4.2.0

### ISSUE THREAD

**Issue by sassur** [juntossomosmais/django-stomp#7]
After installing django-stomp-1.0.1 which in turn installs stomp.py-4.2.0, the command
`python manage.py pubsub "/queue/your-stuff" kliniken.stomp.my_honest_logic`
gives the error
`  File "...\lib\site-packages\django_stomp\services\consumer.py", line 92, in start
    self._connection.start()
AttributeError: 'CustomStompConnection11' object has no attribute 'start'
`

I installed stomp.py-4.1.22 and then i works.

**Comment by IgooorGP** [comment]
Hello @sassur , thanks for reporting this issue.

Right now, we have set `django-stomp` to require `~=4.1`versions of the `stomp.py` lib so that you can continue using `django-stomp` normally.

However, we will soon start working to make `django-stomp` compatible with the version 5.0.0 of `stomp.py`. We will let you know of that, for sure.

**Comment by fabiohk** [comment]
The new released version of `django-stomp` is now compatible with `stomp.py` 6.0.0
